# Base configs
baseurl:
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Alex Haydock | Photos"
subtitle: "My amateur photography."
author: "Alex Haydock"
header:
 title: "Photo Gallery"
 subtitle: "by Alex."